// Vérifie le changement de couleur d'accent en temps réel.
import { chromium } from 'playwright-core'
import { spawn } from 'node:child_process'
const preview = spawn('npx', ['vite', 'preview', '--port', '4179'], { stdio: 'pipe' })
await new Promise(r => setTimeout(r, 2500))
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 }, colorScheme: 'dark', locale: 'fr-FR', timezoneId: 'Europe/Paris' })).newPage()
const errors = []
page.on('pageerror', e => errors.push(e.message))
await page.goto('http://localhost:4179/CAP-Gabriel-/', { waitUntil: 'networkidle' })
await page.getByRole('button', { name: 'Commencer' }).click()
await page.getByRole('button', { name: 'Continuer' }).click()
await page.getByRole('button', { name: 'Continuer' }).click()
await page.getByRole('button', { name: "C'est parti" }).click()
await page.waitForTimeout(300)
await page.getByRole('button', { name: 'Réglages' }).click()
await page.getByRole('button', { name: 'Violet', exact: true }).click()
await page.waitForTimeout(300)
const tint = await page.evaluate(() => getComputedStyle(document.querySelector('.app-shell')).getPropertyValue('--tint').trim())
console.log('tint après Violet =', tint, tint === '#bf5af2' ? 'OK' : 'ÉCHEC')
if (tint !== '#bf5af2') errors.push('accent non appliqué')
await page.screenshot({ path: 'qa-shots/v27-accent.png' })
await page.reload({ waitUntil: 'networkidle' })
await page.waitForTimeout(500)
const tint2 = await page.evaluate(() => getComputedStyle(document.querySelector('.app-shell')).getPropertyValue('--tint').trim())
console.log('tint après rechargement =', tint2, tint2 === '#bf5af2' ? 'OK (persisté)' : 'ÉCHEC')
if (tint2 !== '#bf5af2') errors.push('accent non persisté')
console.log(errors.length ? 'ERREURS: ' + errors.join('; ') : 'ACCENT OK')
await browser.close(); preview.kill(); process.exit(errors.length ? 1 : 0)
