import { chromium } from 'playwright-core'
import { spawn } from 'node:child_process'
const preview = spawn('npx', ['vite', 'preview', '--port', '4177'], { stdio: 'pipe', cwd: '/home/user/CAP-Gabriel-' })
await new Promise(r => setTimeout(r, 2500))
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 }, colorScheme: 'dark', locale: 'fr-FR', timezoneId: 'Europe/Paris' })).newPage()
const errors = []
page.on('pageerror', e => errors.push(e.message))
await page.goto('http://localhost:4177/CAP-Gabriel-/', { waitUntil: 'networkidle' })
await page.getByRole('button', { name: 'Commencer' }).click()
await page.getByRole('button', { name: 'Continuer' }).click()
await page.getByRole('button', { name: 'Continuer' }).click()
await page.getByRole('button', { name: "C'est parti" }).click()
await page.waitForTimeout(300)
await page.getByLabel('Navigation principale').getByRole('button', { name: 'Plan' }).click()
await page.getByRole('button', { name: /Habitudes/ }).click()
await page.getByRole('button', { name: 'Créer une habitude' }).click()
await page.getByLabel('Nom', { exact: true }).fill('Anki')
await page.getByRole('button', { name: 'Enregistrer' }).click()
await page.waitForTimeout(200)
await page.getByRole('button', { name: /Cocher « Anki »/ }).click()
await page.getByLabel('Navigation principale').getByRole('button', { name: 'Moi' }).click()
await page.getByRole('button', { name: /Statistiques/ }).click()
await page.waitForTimeout(600)
await page.screenshot({ path: '/home/user/CAP-Gabriel-/qa-shots/v21-stats.png' })
console.log(errors.length ? 'ERREURS: ' + errors.join('; ') : 'STATS OK')
await browser.close(); preview.kill(); process.exit(errors.length ? 1 : 0)
